import timer from "./modules/timer.js";
import menu from "./modules/menu.js";
import modal from "./modules/modal.js";
import scroll from "./modules/scroll.js";
import form from "./modules/form.js";
import calculator from "./modules/calculator.js";
import tabs from "./modules/tabs.js";
import slider from "./modules/slider.js";
timer("15 may 2024");
menu();
modal();
scroll();
form();
calculator(100);
tabs();
slider();
